/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hayukleung_appjni_JNIInterface.h"
/* Header for class com_hayukleung_appjni_JNIInterface */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hayukleung_appjni_JNIInterface
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_hayukleung_appjni_JNIInterface_stringFromJNI(JNIEnv *env, jobject obj) {
    return (*env)->NewStringUTF(env, "JNIInterface");
}

#ifdef __cplusplus
}
#endif
