/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hayukleung_appjni_JNIInterface */

#ifndef _Included_com_hayukleung_appjni_JNIInterface
#define _Included_com_hayukleung_appjni_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hayukleung_appjni_JNIInterface
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hayukleung_appjni_JNIInterface_stringFromJNI
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
